// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjbbnibpyhfcjskekrbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqYmJuaWJweWhmY2pza2VrcmJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Nzg1NzQsImV4cCI6MjA3MzA1NDU3NH0.eIF5-Z0EkR62XB6esjVtw7LU9ZegSGAIjQc24NY8y0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});